<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="analysis_files/libs/quarto-html/quarto.js"></script>
<script src="analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analysis_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analysis_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="predicting-credit-card-default-behavior" class="level1">
<h1>Predicting Credit Card Default Behavior</h1>
<p>Authors: Daniel Park | Yiting Sun | Jellia Ma | Han Qin</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/c581aee3-c1ec-479a-b42b-79ba6f30224d.png" class="img-fluid figure-img"></p>
<figcaption>image.png</figcaption>
</figure>
</div>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"caret"</span>, <span class="st">"dplyr"</span>, <span class="st">"ggplot2"</span>, <span class="st">"e1071"</span>, <span class="st">"caTools"</span>, <span class="st">"tidyverse"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(class)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>The downloaded binary packages are in
    /var/folders/0p/zs3c69xd4q7d14yr1s25mxjh0000gn/T//RtmpvK87ka/downloaded_packages


Loading required package: ggplot2

Loading required package: lattice


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


── [1mAttaching core tidyverse packages[22m ──────────────────────── tidyverse 2.0.0 ──
[32m✔[39m [34mforcats  [39m 1.0.0     [32m✔[39m [34mstringr  [39m 1.5.1
[32m✔[39m [34mlubridate[39m 1.9.4     [32m✔[39m [34mtibble   [39m 3.2.1
[32m✔[39m [34mpurrr    [39m 1.0.2     [32m✔[39m [34mtidyr    [39m 1.3.1
[32m✔[39m [34mreadr    [39m 2.1.5     
── [1mConflicts[22m ────────────────────────────────────────── tidyverse_conflicts() ──
[31m✖[39m [34mdplyr[39m::[32mfilter()[39m masks [34mstats[39m::filter()
[31m✖[39m [34mdplyr[39m::[32mlag()[39m    masks [34mstats[39m::lag()
[31m✖[39m [34mpurrr[39m::[32mlift()[39m   masks [34mcaret[39m::lift()
[36mℹ[39m Use the conflicted package ([3m[34m&lt;http://conflicted.r-lib.org/&gt;[39m[23m) to force all conflicts to become errors</code></pre>
<section id="i.-summary" class="level2">
<h2 class="anchored" data-anchor-id="i.-summary">I. Summary</h2>
<p>In this study, we developed a classification model to predict whether credit card customers will default based on their demographic features, financial behaviors, and payment history. Using the Default of Credit Card Clients Dataset (https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset/data), we analyzed key factors that contribute to default risk.</p>
<p>Our goal was to build a predictive model that can assist financial institutions in assessing credit risk more effectively. The k-nearest neighbors (KNN) algorithm was implemented to determine whether a customer will default in the next month. The model was trained on historical data, incorporating variables such as given credit limit, repayment status, history payments amount, and demographic characteristics. We evaluated its performance using confusion matrix. The KNN classification model achieved an accuracy of 79.97%, with high sensitivity (93.77%) but low specificity (31.35%), indicating that while the model effectively identifies non-defaulters, it struggles with correctly predicting actual defaulters.</p>
</section>
<section id="ii.-introduction" class="level2">
<h2 class="anchored" data-anchor-id="ii.-introduction">II. Introduction</h2>
<p>By 2023, approximately 1.25 billion people worldwide have credit cards, which is nearly 16% of the global population (Radage, 2023). People rely on credit cards for everyday purchases, financial flexibility, and managing expenses. As credit card usage continues to grow, so does the risk of default, which is a significant concern for financial institutions. Credit card default occurs when a borrower fails to make their minimum payment obligations over an extended period of time (Streaks, 2024). Understanding the factors that contribute to default can help banks and credit card companies make informed lending decisions and develop better risk assessment models. Therefore, our research question is:</p>
<pre><code>Will credit card customers default based on their demographic features, financial behaviours, and payment history?</code></pre>
<p>The dataset used in this study is the Default of Credit Card Clients Dataset from the UCI Machine Learning Repository, which contains 30000 observations and 24 features, including information on credit limit, demographic factors, history of payment, and bill statements of credit card clients in Taiwan from April 2005 to September 2005. The target variable default.payment.next.month indicates whether a customer defaulted (1) or not (0).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 60%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>CREDIT_LIMIT</code></td>
<td>Amount of given credit in NT dollars</td>
</tr>
<tr class="even">
<td><code>SEX</code></td>
<td>Gender (1=male, 2=female)</td>
</tr>
<tr class="odd">
<td><code>EDUCATION</code></td>
<td>Measure of education levels (1=graduate school, 2=university, 3=high school, 4=others, 5=unknown, 6=unknown)</td>
</tr>
<tr class="even">
<td><code>MARRIAGE</code></td>
<td>Marital status (1=married, 2=single, 3=others)</td>
</tr>
<tr class="odd">
<td><code>AGE</code></td>
<td>Age in years</td>
</tr>
<tr class="even">
<td><code>PAY_0</code></td>
<td>Repayment status in September, 2005 (-1=pay duly, 1=payment delay for one month, 2=payment delay for two months, … 8=payment delay for eight months, 9=payment delay for nine months and above)</td>
</tr>
<tr class="odd">
<td><code>PAY_2</code></td>
<td>Repayment status in August, 2005 (scale same as above)</td>
</tr>
<tr class="even">
<td><code>PAY_3</code></td>
<td>Repayment status in July, 2005 (scale same as above)</td>
</tr>
<tr class="odd">
<td><code>PAY_4</code></td>
<td>Repayment status in June, 2005 (scale same as above)</td>
</tr>
<tr class="even">
<td><code>PAY_5</code></td>
<td>Repayment status in May, 2005 (scale same as above)</td>
</tr>
<tr class="odd">
<td><code>PAY_6</code></td>
<td>Repayment status in April, 2005 (scale same as above)</td>
</tr>
<tr class="even">
<td><code>AVG_BILL_AMT</code></td>
<td>Average amount of bill statement from April to September, 2005 (in NT dollar)</td>
</tr>
<tr class="odd">
<td><code>AVG_PAY_AMT</code></td>
<td>Average amount of previous payment from April to September, 2005 (in NT dollar)</td>
</tr>
</tbody>
</table>
<p>Table 1 - Selected and mutated predictor variables used for analysis</p>
</section>
<section id="iii.-methods-results" class="level2">
<h2 class="anchored" data-anchor-id="iii.-methods-results">III. Methods &amp; Results</h2>
<section id="data-preprocessing" class="level3">
<h3 class="anchored" data-anchor-id="data-preprocessing">Data Preprocessing</h3>
<ul>
<li>Cleaning &amp; Handling missing values &amp; Feature scaling &amp; Train-test split.</li>
</ul>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Read Data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/UCI_Credit_Card.csv"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="dataframe table table-sm table-striped small">
<caption>
A data.frame: 6 × 25
</caption>
<thead>
<tr>
<th>
</th>
<th scope="col">
ID
</th>
<th scope="col">
LIMIT_BAL
</th>
<th scope="col">
SEX
</th>
<th scope="col">
EDUCATION
</th>
<th scope="col">
MARRIAGE
</th>
<th scope="col">
AGE
</th>
<th scope="col">
PAY_0
</th>
<th scope="col">
PAY_2
</th>
<th scope="col">
PAY_3
</th>
<th scope="col">
PAY_4
</th>
<th scope="col">
⋯
</th>
<th scope="col">
BILL_AMT4
</th>
<th scope="col">
BILL_AMT5
</th>
<th scope="col">
BILL_AMT6
</th>
<th scope="col">
PAY_AMT1
</th>
<th scope="col">
PAY_AMT2
</th>
<th scope="col">
PAY_AMT3
</th>
<th scope="col">
PAY_AMT4
</th>
<th scope="col">
PAY_AMT5
</th>
<th scope="col">
PAY_AMT6
</th>
<th scope="col">
default.payment.next.month
</th>
</tr>
<tr>
<th>
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
⋯
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">
1
</th>
<td>
1
</td>
<td>
20000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
1
</td>
<td>
24
</td>
<td>
2
</td>
<td>
2
</td>
<td>
-1
</td>
<td>
-1
</td>
<td>
⋯
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
689
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
1
</td>
</tr>
<tr>
<th scope="row">
2
</th>
<td>
2
</td>
<td>
120000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
2
</td>
<td>
26
</td>
<td>
-1
</td>
<td>
2
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
3272
</td>
<td>
3455
</td>
<td>
3261
</td>
<td>
0
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
0
</td>
<td>
2000
</td>
<td>
1
</td>
</tr>
<tr>
<th scope="row">
3
</th>
<td>
3
</td>
<td>
90000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
2
</td>
<td>
34
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
14331
</td>
<td>
14948
</td>
<td>
15549
</td>
<td>
1518
</td>
<td>
1500
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
5000
</td>
<td>
0
</td>
</tr>
<tr>
<th scope="row">
4
</th>
<td>
4
</td>
<td>
50000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
1
</td>
<td>
37
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
28314
</td>
<td>
28959
</td>
<td>
29547
</td>
<td>
2000
</td>
<td>
2019
</td>
<td>
1200
</td>
<td>
1100
</td>
<td>
1069
</td>
<td>
1000
</td>
<td>
0
</td>
</tr>
<tr>
<th scope="row">
5
</th>
<td>
5
</td>
<td>
50000
</td>
<td>
1
</td>
<td>
2
</td>
<td>
1
</td>
<td>
57
</td>
<td>
-1
</td>
<td>
0
</td>
<td>
-1
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
20940
</td>
<td>
19146
</td>
<td>
19131
</td>
<td>
2000
</td>
<td>
36681
</td>
<td>
10000
</td>
<td>
9000
</td>
<td>
689
</td>
<td>
679
</td>
<td>
0
</td>
</tr>
<tr>
<th scope="row">
6
</th>
<td>
6
</td>
<td>
50000
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
37
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
19394
</td>
<td>
19619
</td>
<td>
20024
</td>
<td>
2500
</td>
<td>
1815
</td>
<td>
657
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
800
</td>
<td>
0
</td>
</tr>
</tbody>
</table>
<p>Table 2 - Preview of original data set</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove unnecessary columns (e.g., ID)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>ID)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Split into training (80%) and testing (20%)</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>split <span class="ot">&lt;-</span> <span class="fu">sample.split</span>(df<span class="sc">$</span>default.payment.next.month, <span class="at">SplitRatio =</span> <span class="fl">0.8</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>train_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, split <span class="sc">==</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>test_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, split <span class="sc">==</span> <span class="cn">FALSE</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the dimensions of training data</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(train_df)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Check class distribution</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(train_df<span class="sc">$</span>default.payment.next.month) <span class="sc">/</span> <span class="fu">nrow</span>(train_df)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(train_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<style>
.list-inline {list-style: none; margin:0; padding: 0}
.list-inline>li {display: inline-block}
.list-inline>li:not(:last-child)::after {content: "\00b7"; padding: 0 .5ex}
</style>
<ol class="list-inline">
<li>
24000
</li>
<li>
24
</li>
</ol>
<pre><code>        0         1 
0.7787917 0.2212083 



   LIMIT_BAL           SEX          EDUCATION        MARRIAGE    
 Min.   : 10000   Min.   :1.000   Min.   :0.000   Min.   :0.000  
 1st Qu.: 50000   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:1.000  
 Median :140000   Median :2.000   Median :2.000   Median :2.000  
 Mean   :168505   Mean   :1.603   Mean   :1.856   Mean   :1.547  
 3rd Qu.:240000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000  
 Max.   :800000   Max.   :2.000   Max.   :6.000   Max.   :3.000  
      AGE            PAY_0              PAY_2             PAY_3        
 Min.   :21.00   Min.   :-2.00000   Min.   :-2.0000   Min.   :-2.0000  
 1st Qu.:28.00   1st Qu.:-1.00000   1st Qu.:-1.0000   1st Qu.:-1.0000  
 Median :34.00   Median : 0.00000   Median : 0.0000   Median : 0.0000  
 Mean   :35.54   Mean   :-0.01708   Mean   :-0.1327   Mean   :-0.1656  
 3rd Qu.:41.00   3rd Qu.: 0.00000   3rd Qu.: 0.0000   3rd Qu.: 0.0000  
 Max.   :79.00   Max.   : 8.00000   Max.   : 8.0000   Max.   : 8.0000  
     PAY_4             PAY_5             PAY_6           BILL_AMT1      
 Min.   :-2.0000   Min.   :-2.0000   Min.   :-2.0000   Min.   :-165580  
 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:   3580  
 Median : 0.0000   Median : 0.0000   Median : 0.0000   Median :  22450  
 Mean   :-0.2211   Mean   :-0.2623   Mean   :-0.2872   Mean   :  51553  
 3rd Qu.: 0.0000   3rd Qu.: 0.0000   3rd Qu.: 0.0000   3rd Qu.:  67620  
 Max.   : 8.0000   Max.   : 8.0000   Max.   : 8.0000   Max.   : 746814  
   BILL_AMT2        BILL_AMT3         BILL_AMT4         BILL_AMT5     
 Min.   :-69777   Min.   : -61506   Min.   :-170000   Min.   :-81334  
 1st Qu.:  3058   1st Qu.:   2700   1st Qu.:   2338   1st Qu.:  1823  
 Median : 21466   Median :  20198   Median :  19104   Median : 18136  
 Mean   : 49555   Mean   :  47270   Mean   :  43490   Mean   : 40515  
 3rd Qu.: 64678   3rd Qu.:  60931   3rd Qu.:  54900   3rd Qu.: 50424  
 Max.   :743970   Max.   :1664089   Max.   : 616836   Max.   :823540  
   BILL_AMT6          PAY_AMT1         PAY_AMT2          PAY_AMT3     
 Min.   :-339603   Min.   :     0   Min.   :      0   Min.   :     0  
 1st Qu.:   1300   1st Qu.:  1000   1st Qu.:    840   1st Qu.:   400  
 Median :  17206   Median :  2132   Median :   2012   Median :  1855  
 Mean   :  39145   Mean   :  5659   Mean   :   5953   Mean   :  5233  
 3rd Qu.:  49543   3rd Qu.:  5015   3rd Qu.:   5000   3rd Qu.:  4582  
 Max.   : 699944   Max.   :873552   Max.   :1684259   Max.   :889043  
    PAY_AMT4         PAY_AMT5         PAY_AMT6       
 Min.   :     0   Min.   :     0   Min.   :     0.0  
 1st Qu.:   300   1st Qu.:   279   1st Qu.:   143.8  
 Median :  1500   Median :  1522   Median :  1500.0  
 Mean   :  4850   Mean   :  4883   Mean   :  5292.9  
 3rd Qu.:  4012   3rd Qu.:  4105   3rd Qu.:  4003.0  
 Max.   :621000   Max.   :426529   Max.   :528666.0  
 default.payment.next.month
 Min.   :0.0000            
 1st Qu.:0.0000            
 Median :0.0000            
 Mean   :0.2212            
 3rd Qu.:0.0000            
 Max.   :1.0000            </code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(train_df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>0</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instead of using each day's amount we compute the average of BILL_AMT and PAY_AMT columns to make it more organized</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>train_df<span class="sc">$</span>AVG_BILL_AMT <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(train_df[, <span class="fu">grep</span>(<span class="st">"BILL_AMT"</span>, <span class="fu">names</span>(train_df))])</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>train_df<span class="sc">$</span>AVG_PAY_AMT <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(train_df[, <span class="fu">grep</span>(<span class="st">"PAY_AMT"</span>, <span class="fu">names</span>(train_df))])</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>test_df<span class="sc">$</span>AVG_BILL_AMT <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(test_df[, <span class="fu">grep</span>(<span class="st">"BILL_AMT"</span>, <span class="fu">names</span>(test_df))])</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>test_df<span class="sc">$</span>AVG_PAY_AMT <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(test_df[, <span class="fu">grep</span>(<span class="st">"PAY_AMT"</span>, <span class="fu">names</span>(test_df))])</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="dataframe table table-sm table-striped small">
<caption>
A data.frame: 6 × 26
</caption>
<thead>
<tr>
<th>
</th>
<th scope="col">
LIMIT_BAL
</th>
<th scope="col">
SEX
</th>
<th scope="col">
EDUCATION
</th>
<th scope="col">
MARRIAGE
</th>
<th scope="col">
AGE
</th>
<th scope="col">
PAY_0
</th>
<th scope="col">
PAY_2
</th>
<th scope="col">
PAY_3
</th>
<th scope="col">
PAY_4
</th>
<th scope="col">
PAY_5
</th>
<th scope="col">
⋯
</th>
<th scope="col">
BILL_AMT6
</th>
<th scope="col">
PAY_AMT1
</th>
<th scope="col">
PAY_AMT2
</th>
<th scope="col">
PAY_AMT3
</th>
<th scope="col">
PAY_AMT4
</th>
<th scope="col">
PAY_AMT5
</th>
<th scope="col">
PAY_AMT6
</th>
<th scope="col">
default.payment.next.month
</th>
<th scope="col">
AVG_BILL_AMT
</th>
<th scope="col">
AVG_PAY_AMT
</th>
</tr>
<tr>
<th>
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
⋯
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">
1
</th>
<td>
20000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
1
</td>
<td>
24
</td>
<td>
2
</td>
<td>
2
</td>
<td>
-1
</td>
<td>
-1
</td>
<td>
-2
</td>
<td>
⋯
</td>
<td>
0
</td>
<td>
0
</td>
<td>
689
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
1
</td>
<td>
1284.000
</td>
<td>
114.8333
</td>
</tr>
<tr>
<th scope="row">
2
</th>
<td>
120000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
2
</td>
<td>
26
</td>
<td>
-1
</td>
<td>
2
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
3261
</td>
<td>
0
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
0
</td>
<td>
2000
</td>
<td>
1
</td>
<td>
2846.167
</td>
<td>
833.3333
</td>
</tr>
<tr>
<th scope="row">
3
</th>
<td>
90000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
2
</td>
<td>
34
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
15549
</td>
<td>
1518
</td>
<td>
1500
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
5000
</td>
<td>
0
</td>
<td>
16942.167
</td>
<td>
1836.3333
</td>
</tr>
<tr>
<th scope="row">
5
</th>
<td>
50000
</td>
<td>
1
</td>
<td>
2
</td>
<td>
1
</td>
<td>
57
</td>
<td>
-1
</td>
<td>
0
</td>
<td>
-1
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
19131
</td>
<td>
2000
</td>
<td>
36681
</td>
<td>
10000
</td>
<td>
9000
</td>
<td>
689
</td>
<td>
679
</td>
<td>
0
</td>
<td>
18223.167
</td>
<td>
9841.5000
</td>
</tr>
<tr>
<th scope="row">
6
</th>
<td>
50000
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
37
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
20024
</td>
<td>
2500
</td>
<td>
1815
</td>
<td>
657
</td>
<td>
1000
</td>
<td>
1000
</td>
<td>
800
</td>
<td>
0
</td>
<td>
39685.667
</td>
<td>
1295.3333
</td>
</tr>
<tr>
<th scope="row">
7
</th>
<td>
500000
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
29
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
⋯
</td>
<td>
473944
</td>
<td>
55000
</td>
<td>
40000
</td>
<td>
38000
</td>
<td>
20239
</td>
<td>
13750
</td>
<td>
13770
</td>
<td>
0
</td>
<td>
454099.167
</td>
<td>
30126.5000
</td>
</tr>
</tbody>
</table>
<p>Table 3 - Preview of cleaned training dataset</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove original BILL_AMT and PAY_AMT columns to make it look clean</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>train_df <span class="ot">&lt;-</span> train_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"BILL_AMT"</span>), <span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"PAY_AMT"</span>))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>test_df <span class="ot">&lt;-</span> test_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"BILL_AMT"</span>), <span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"PAY_AMT"</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename LIMIT_BAL to CREDIT_LIMIT to make it more readable</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>train_df <span class="ot">&lt;-</span> <span class="fu">rename</span>(train_df, <span class="at">CREDIT_LIMIT =</span> LIMIT_BAL)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>test_df <span class="ot">&lt;-</span> <span class="fu">rename</span>(test_df, <span class="at">CREDIT_LIMIT =</span> LIMIT_BAL)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="dataframe table table-sm table-striped small">
<caption>
A data.frame: 6 × 14
</caption>
<thead>
<tr>
<th>
</th>
<th scope="col">
CREDIT_LIMIT
</th>
<th scope="col">
SEX
</th>
<th scope="col">
EDUCATION
</th>
<th scope="col">
MARRIAGE
</th>
<th scope="col">
AGE
</th>
<th scope="col">
PAY_0
</th>
<th scope="col">
PAY_2
</th>
<th scope="col">
PAY_3
</th>
<th scope="col">
PAY_4
</th>
<th scope="col">
PAY_5
</th>
<th scope="col">
PAY_6
</th>
<th scope="col">
default.payment.next.month
</th>
<th scope="col">
AVG_BILL_AMT
</th>
<th scope="col">
AVG_PAY_AMT
</th>
</tr>
<tr>
<th>
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;int&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
<th scope="col">
&lt;dbl&gt;
</th>
</tr>
</thead>
<tbody>
<tr>
<th scope="row">
1
</th>
<td>
20000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
1
</td>
<td>
24
</td>
<td>
2
</td>
<td>
2
</td>
<td>
-1
</td>
<td>
-1
</td>
<td>
-2
</td>
<td>
-2
</td>
<td>
1
</td>
<td>
1284.000
</td>
<td>
114.8333
</td>
</tr>
<tr>
<th scope="row">
2
</th>
<td>
120000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
2
</td>
<td>
26
</td>
<td>
-1
</td>
<td>
2
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
2
</td>
<td>
1
</td>
<td>
2846.167
</td>
<td>
833.3333
</td>
</tr>
<tr>
<th scope="row">
3
</th>
<td>
90000
</td>
<td>
2
</td>
<td>
2
</td>
<td>
2
</td>
<td>
34
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
16942.167
</td>
<td>
1836.3333
</td>
</tr>
<tr>
<th scope="row">
5
</th>
<td>
50000
</td>
<td>
1
</td>
<td>
2
</td>
<td>
1
</td>
<td>
57
</td>
<td>
-1
</td>
<td>
0
</td>
<td>
-1
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
18223.167
</td>
<td>
9841.5000
</td>
</tr>
<tr>
<th scope="row">
6
</th>
<td>
50000
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
37
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
39685.667
</td>
<td>
1295.3333
</td>
</tr>
<tr>
<th scope="row">
7
</th>
<td>
500000
</td>
<td>
1
</td>
<td>
1
</td>
<td>
2
</td>
<td>
29
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
0
</td>
<td>
454099.167
</td>
<td>
30126.5000
</td>
</tr>
</tbody>
</table>
<p>Table 4 - Preview of cleaned training dataset</p>
</section>
<section id="exploratory-data-analysis-eda" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</h3>
<ul>
<li>Visualization for distribution of target variable, brief view of relationship between target variable and exploratory variables.</li>
</ul>
<div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the target variable to a factor for better visualization</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width =</span> <span class="dv">10</span>, <span class="at">repr.plot.height =</span> <span class="dv">6</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>train_df<span class="sc">$</span>default.payment.next.month <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(train_df<span class="sc">$</span>default.payment.next.month)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Distribution of default payments</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>target_dis <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(train_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(default.payment.next.month))) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Default Payments"</span>, <span class="at">x =</span> <span class="st">"Default (0 = No, 1 = Yes)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>target_dis</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/analysis_17_0.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
<p>Figure 1 - Distribution of default payments</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width =</span> <span class="dv">20</span>, <span class="at">repr.plot.height =</span> <span class="dv">15</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the dataset for facet grid visualization</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>df_long <span class="ot">&lt;-</span> train_df <span class="sc">%&gt;%</span> </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(CREDIT_LIMIT, AGE, AVG_BILL_AMT, AVG_PAY_AMT, PAY_0),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"Feature"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plots using facet grid with color for default class and trend lines, showing all the general distribution</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># btw numeric variables and the target variable</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_long, <span class="fu">aes</span>(<span class="at">x =</span> Value, <span class="at">y =</span> default.payment.next.month, <span class="at">color =</span> default.payment.next.month)) <span class="sc">+</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Feature, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter Plots of Numeric Features vs Default Payment"</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Feature Value"</span>, <span class="at">y =</span> <span class="st">"Default Payment (0 = No, 1 = Yes)"</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Default Status"</span>)  <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),   </span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),    </span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>),   </span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),  </span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>)) </span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>[1m[22m`geom_smooth()` using formula = 'y ~ x'</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/analysis_19_1.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
<p>Figure 2 - Scatter plots using facet grid with color for default class and trend lines, showing all the general distribution between numeric variables and the target variable</p>
</section>
<section id="model-training" class="level3">
<h3 class="anchored" data-anchor-id="model-training">Model Training</h3>
<div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width =</span> <span class="dv">12</span>, <span class="at">repr.plot.height =</span> <span class="dv">10</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Define normalization function</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>normalize <span class="ot">&lt;-</span> <span class="cf">function</span>(x) { (x <span class="sc">-</span> <span class="fu">min</span>(x)) <span class="sc">/</span> (<span class="fu">max</span>(x) <span class="sc">-</span> <span class="fu">min</span>(x)) }</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Select only numeric columns for normalization (excluding the target variable)</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>numeric_columns <span class="ot">&lt;-</span> <span class="fu">sapply</span>(train_df, is.numeric)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract target variable BEFORE normalization</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>train_labels <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(train_df<span class="sc">$</span>default.payment.next.month) </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>test_labels <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(test_df<span class="sc">$</span>default.payment.next.month)    </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply normalization only to numeric columns (excluding the target variable)</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>train_df_norm <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(train_df[, numeric_columns], normalize))</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>test_df_norm <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">lapply</span>(test_df[, numeric_columns], normalize))</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the target variable from the normalized data (it should NOT be included in knn predictors)</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>train_df_norm <span class="ot">&lt;-</span> train_df_norm[, <span class="fu">colnames</span>(train_df_norm) <span class="sc">!=</span> <span class="st">"default.payment.next.month"</span>]</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>test_df_norm <span class="ot">&lt;-</span> test_df_norm[, <span class="fu">colnames</span>(test_df_norm) <span class="sc">!=</span> <span class="st">"default.payment.next.month"</span>]</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Try different k values and store accuracy results</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>k_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">20</span>, <span class="at">by =</span> <span class="dv">1</span>)  <span class="co"># Testing k from 1 to 20</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>accuracy_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">k =</span> k_values, <span class="at">accuracy =</span> <span class="cn">NA</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(k_values)) {</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>  knn_pred <span class="ot">&lt;-</span> <span class="fu">knn</span>(<span class="at">train =</span> train_df_norm, <span class="at">test =</span> test_df_norm, <span class="at">cl =</span> train_labels, <span class="at">k =</span> k_values[i])</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a> <span class="co"># Calculate accuracy</span></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>  accuracy_results<span class="sc">$</span>accuracy[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(knn_pred <span class="sc">==</span> test_labels) <span class="sc">/</span> <span class="fu">length</span>(test_labels)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the best k (highest accuracy)</span></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>best_k <span class="ot">&lt;-</span> accuracy_results<span class="sc">$</span>k[<span class="fu">which.max</span>(accuracy_results<span class="sc">$</span>accuracy)]</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Best k value:"</span>, best_k, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot accuracy vs. k to visualize the best k choice</span></span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(accuracy_results, <span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> accuracy)) <span class="sc">+</span></span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"K-Value Selection for KNN"</span>,</span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Number of Neighbors (k)"</span>,</span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Accuracy"</span>) <span class="sc">+</span></span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Train KNN Model </span></span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a>knn_model <span class="ot">&lt;-</span> <span class="fu">knn</span>(<span class="at">train =</span> train_df_norm, <span class="at">test =</span> test_df_norm, <span class="at">cl =</span> train_labels, <span class="at">k =</span> best_k)</span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate Model Performance</span></span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> knn_model, <span class="at">Actual =</span> test_labels)</span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(conf_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Best k value: 18 
         Actual
Predicted    0    1
        0 4382  911
        1  291  416</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="analysis_files/analysis_22_1.png" class="img-fluid figure-img"></p>
<figcaption>png</figcaption>
</figure>
</div>
<p>Figure 3 - K-Value Selection for KNN</p>
</section>
<section id="performance-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="performance-evaluation">Performance Evaluation</h3>
<ul>
<li>Accuracy &amp; confusion matrix.</li>
</ul>
<div class="sourceCode" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Accuracy, Precision, confusion matrix</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>confusion <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="fu">as.factor</span>(knn_model), <span class="fu">as.factor</span>(test_labels))</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 4382  911
         1  291  416
                                          
               Accuracy : 0.7997          
                 95% CI : (0.7893, 0.8097)
    No Information Rate : 0.7788          
    P-Value [Acc &gt; NIR] : 4.517e-05       
                                          
                  Kappa : 0.3017          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.9377          
            Specificity : 0.3135          
         Pos Pred Value : 0.8279          
         Neg Pred Value : 0.5884          
             Prevalence : 0.7788          
         Detection Rate : 0.7303          
   Detection Prevalence : 0.8822          
      Balanced Accuracy : 0.6256          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</section>
</section>
<section id="iv.-discussion" class="level2">
<h2 class="anchored" data-anchor-id="iv.-discussion">IV. Discussion</h2>
<section id="summary-of-result" class="level4">
<h4 class="anchored" data-anchor-id="summary-of-result">Summary of Result:</h4>
<p>The best k-value for the K-Nearest Neighbors (KNN) model was determined to be 18. The plot above shows that as k increases, the accuracy stabilizes around 80%, suggesting an optimal balance between underfitting and overfitting.</p>
<p>Our K-Nearest Neighbors (KNN) classification model achieved an accuracy of 79.97%, indicating that it correctly predicts default and non-default cases in about 80% of instances. However, the model performs significantly better at identifying non-defaulters (sensitivity: 93.77%) than defaulters (specificity: 31.35%). The confusion matrix reveals a high false negative rate (911 cases), meaning that many actual defaulters were misclassified as non-defaulters. The balanced accuracy of 62.56% suggests that the model struggles with class imbalance, favoring the majority class (non-defaulters). To improve the result, we could use techniques to balance the dataset and try other classification models.</p>
</section>
<section id="expectations" class="level4">
<h4 class="anchored" data-anchor-id="expectations">Expectations:</h4>
<p>These results are partially expected. Since credit card defaults are typically imbalanced datasets, it was anticipated that the model might struggle with detecting defaulters. However, the low specificity was lower than expected, meaning the model fails to accurately identify defaulters more frequently than anticipated. - We expected some bias toward the majority class (non-defaulters), but the high false negative rate suggests that KNN may not be the most effective method for this classification problem.</p>
</section>
<section id="impact-of-findings" class="level4">
<h4 class="anchored" data-anchor-id="impact-of-findings">Impact of Findings:</h4>
<p>Ideally, the model can serve as a valuable tool for financial institutions in assessing credit risk and making informed lending decisions. Effectively distinguish between defaulters and non-defaulters, reducing financial losses by minimizing the risk of approving loans for high-risk individuals. However, in our model, the high false negative rate poses a risk to financial institutions, as they might approve loans for individuals who are likely to default. The low specificity could result in misleading credit scores, potentially granting loans to individuals who are unable to repay while unfairly rejecting creditworthy applicants. These findings highlight the need for improving predictive models.</p>
</section>
<section id="future-questions" class="level4">
<h4 class="anchored" data-anchor-id="future-questions">Future Questions:</h4>
<ul>
<li>How do external economic factors impact default rates?
<ul>
<li>Our model focuses on individual demographic and financial characteristics, but macroeconomic conditions such as inflation, interest rates, and unemployment rates could also play a crucial role in credit card default. Some existing studies have shown that “credit card default is not related to the amount of credit card customer’s income, but significantly to the stability of income” (Li et al., 2019). Future studies could incorporate these external factors to improve predictive accuracy.</li>
</ul></li>
<li>Can other algorithms improve prediction accuracy?
<ul>
<li>While KNN provides useful insights, exploring other classification models such as logistic regression, decision trees, etc. may yield better performance. A comparative analysis could determine the most effective model for predicting defaults.</li>
</ul></li>
<li>How does financial behavior change over time, and can we predict long-term default risk?
<ul>
<li>Our model predicts default based on a fixed time period, but analyzing customer behavior over longer durations could reveal trends in financial stability.</li>
</ul></li>
</ul>
</section>
</section>
<section id="v.-references" class="level2">
<h2 class="anchored" data-anchor-id="v.-references">V. References</h2>
<p>ICI.Radio-Canada.ca, Z. É.-. (n.d.). What you need to know about the new credit card surcharge: RCI. Radio. https://ici.radio-canada.ca/rci/en/news/1923776/what-you-need-to-know-about-the-new-credit-card-surcharge</p>
<p>Learning, U. M. (2016, November 3). Default of credit card clients dataset. Kaggle. https://www.kaggle.com/datasets/uciml/default-of-credit-card-clients-dataset/data</p>
<p>Li, Y., Li, Y., &amp; Li, Y. (2019). What factors are influencing credit card customer’s default behavior in China? A study based on survival analysis. Physica A: Statistical Mechanics and Its Applications, 526, 120861. https://doi.org/10.1016/j.physa.2019.04.097</p>
<p>Radage, K. (2023, July 31). The growth of the credit card industry in 2023. Credit Card Processing and Merchant Account. https://www.clearlypayments.com/blog/growth-of-credit-card-industry-in-2023/</p>
<p>Streaks, J. (n.d.). What is a credit card default? A complete guide. Business Insider. https://www.businessinsider.com/personal-finance/credit-score/what-is-a-credit-card-default</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>